GET http://127.0.0.1:8001/api/clients

###

GET http://127.0.0.1:8001/api/clients/1

###

POST http://127.0.0.1:8001/api/clients
Content-Type: application/json

{
    "nom": "test1",
    "prenom": "test2",
    "ville": "test34"
}

###

PUT http://127.0.0.1:8001/api/clients/13

{
    "ville": "dd"
}


###

DELETE http://127.0.0.1:8001/api/clients/13

